[package]
name = "clvm_rs"
version = "0.1.8"
authors = ["Richard Kiss <him@richardkiss.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "clvm_rs"
crate-type = ["cdylib"]

[profile.release]
lto = true

[features]
extension-module = ["pyo3", "pyo3/extension-module"]
default = ["sha2"]

[dependencies]
hex = "0.4.2"
lazy_static = "1.4.0"
num-bigint = "0.3.1"
bls12_381 = "0.4.0"
pyo3 = { version = "0.14.1", optional = true }
sha2 = { version = "0.8.0", optional = true }

[target.'cfg(unix)'.dependencies]
openssl = { version = "0.10.32", features = ["vendored"], optional = true }
