[build-system]
requires = ["maturin>=0.11,<0.12"]
build-backend = "maturin"

[tool.maturin]
bindings = "pyo3"
manylinux = "2010"
cargo-extra-args = "--features extension-module,openssl"

[lib]
crate-type = ["cdylib"]
