name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9' ]
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # we need fetch-depth 0 so setuptools_scm can resolve tags
      - name: Set up rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev]
      - name: Test with pytest
        run: |
          py.test tests
